import { Link, useParams } from 'react-router-dom';
import { getOrder } from '../utils/shop';
import './OrderDetails.css';

export default function OrderDetails() {
  const { id } = useParams();
  const order = getOrder(id);
  if (!order) return <div className="order-page"><Link className="text-link" to="/order-history">&#8592; Back to order history</Link><div className="empty-shop"><h2>Order not found</h2><p>This order may have been cleared from this browser.</p><Link className="btn-primary" to="/order-history">View order history</Link></div></div>;
  const placedAt = new Date(order.createdAt).toLocaleString(undefined, { dateStyle: 'long', timeStyle: 'short' });
  return <div className="order-page"><Link className="text-link" to="/order-history">&#8592; Back to order history</Link><header className="order-heading"><div><span className="shop-eyebrow">ORDER CONFIRMATION</span><h1>{order.id}</h1><p>Placed {placedAt}</p></div><span className="order-status">{order.status}</span></header><div className="order-details-grid"><section className="order-card"><div className="order-card-heading"><h2>Items in this order</h2><span>{order.items.length} {order.items.length === 1 ? 'item' : 'items'}</span></div>{order.items.map((item) => <div className="order-item" key={item.id}><div className="order-item-image">{item.image ? <img src={item.image} alt="" /> : <span>+</span>}</div><div><h3>{item.name}</h3><p>{item.seller || 'Student seller'}{item.category ? ` · ${item.category}` : ''}</p><span>Quantity: {item.quantity || 1}</span></div><strong>R{(Number(item.price) * Number(item.quantity || 1)).toFixed(2)}</strong></div>)}<div className="order-safe-banner"><strong>Meet safely on campus</strong><span>Choose a public location and confirm the meetup with the seller in Messages.</span></div></section><aside><section className="order-card order-summary-card"><h2>Order summary</h2><div><span>Subtotal</span><strong>R{Number(order.total).toFixed(2)}</strong></div><div><span>Meet-up</span><span className="free-label">Free</span></div><hr /><div className="summary-total"><span>Total</span><strong>R{Number(order.total).toFixed(2)}</strong></div></section><section className="order-card"><h2>Collection details</h2><p className="order-detail-label">Meet-up location</p><strong>{order.meetupLocation}</strong><p className="order-detail-label">Payment method</p><strong>{order.paymentMethod}</strong></section></aside></div></div>;
}
